"""
PDF generator for court-ready evidence reports.
Uses ReportLab to produce structured, professional PDFs.
Supports DE + EN, includes all evidence, classification, and legal references.
"""

import io
from datetime import datetime, timezone
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)

from app.models.evidence import Case, EvidenceItem, Severity


def generate_pdf(case: Case, report_type: str = "general", lang: str = "de") -> bytes:
    """Generate a court-ready PDF report for a case."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=25 * mm, rightMargin=25 * mm,
        topMargin=20 * mm, bottomMargin=20 * mm,
    )

    styles = _get_styles()
    is_de = lang == "de"
    elements = []

    # Header
    elements.append(Paragraph("SafeVoice", styles["Title"]))
    elements.append(Paragraph(
        "Dokumentationsplattform für digitale Gewalt" if is_de
        else "Digital Violence Documentation Platform",
        styles["Subtitle"]
    ))
    elements.append(Spacer(1, 8 * mm))

    # Report type banner
    type_labels = {
        "general": ("Beweissicherungsbericht", "Evidence Documentation Report"),
        "netzdg": ("NetzDG-Meldung", "NetzDG Report"),
        "police": ("Strafanzeige – Vorlage", "Criminal Complaint – Template"),
    }
    label = type_labels.get(report_type, type_labels["general"])
    elements.append(Paragraph(label[0] if is_de else label[1], styles["ReportType"]))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#4338ca")))
    elements.append(Spacer(1, 6 * mm))

    # Case metadata
    now = datetime.now(timezone.utc)
    meta_data = [
        [_l("Fall-ID", "Case ID", is_de), case.id],
        [_l("Erstellt", "Created", is_de), _fmt_dt(case.created_at, is_de)],
        [_l("Bericht generiert", "Report generated", is_de), _fmt_dt(now, is_de)],
        [_l("Schweregrad", "Severity", is_de), _severity_label(case.overall_severity, is_de)],
        [_l("Beweise", "Evidence items", is_de), str(len(case.evidence_items))],
        [_l("Status", "Status", is_de), case.status],
    ]
    meta_table = Table(meta_data, colWidths=[55 * mm, 105 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#64748b")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1e293b")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 6 * mm))

    # Victim context
    if case.victim_context:
        elements.append(Paragraph(
            _l("Kontext der betroffenen Person", "Victim context", is_de),
            styles["SectionHead"]
        ))
        elements.append(Paragraph(case.victim_context, styles["Body"]))
        elements.append(Spacer(1, 4 * mm))

    # Pattern flags
    if case.pattern_flags:
        elements.append(Paragraph(
            _l("Erkannte Muster", "Detected patterns", is_de),
            styles["SectionHead"]
        ))
        for flag in case.pattern_flags:
            desc = flag.description_de if is_de else flag.description
            elements.append(Paragraph(
                f"<b>⚑ {flag.type}</b> ({_severity_label(flag.severity, is_de)}): {desc}",
                styles["Body"]
            ))
        elements.append(Spacer(1, 4 * mm))

    # Evidence items
    elements.append(Paragraph(
        _l("Beweismittel", "Evidence", is_de),
        styles["SectionHead"]
    ))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1")))
    elements.append(Spacer(1, 3 * mm))

    for i, ev in enumerate(case.evidence_items, 1):
        elements.extend(_evidence_block(ev, i, is_de, styles))
        if i < len(case.evidence_items):
            elements.append(HRFlowable(
                width="100%", thickness=0.3, color=colors.HexColor("#e2e8f0"), spaceAfter=3 * mm
            ))

    # Legal notice
    elements.append(Spacer(1, 8 * mm))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#4338ca")))
    elements.append(Spacer(1, 3 * mm))
    elements.append(Paragraph(
        _l(
            "Dieser Bericht wurde automatisch von SafeVoice generiert. "
            "Alle Inhalte sind mit SHA-256 Prüfsummen gesichert. "
            "Die Archivierungslinks dienen als unabhängiger Nachweis der Existenz der Inhalte zum Erfassungszeitpunkt.",
            "This report was automatically generated by SafeVoice. "
            "All content is secured with SHA-256 checksums. "
            "Archive links serve as independent proof of content existence at the time of capture.",
            is_de
        ),
        styles["Footer"]
    ))

    doc.build(elements)
    return buf.getvalue()


def _evidence_block(ev: EvidenceItem, idx: int, is_de: bool, styles: dict) -> list:
    """Build a section for a single evidence item."""
    elements = []
    c = ev.classification

    elements.append(Paragraph(
        f"{_l('Beweis', 'Evidence', is_de)} #{idx} — @{ev.author_username}",
        styles["EvidenceHead"]
    ))
    elements.append(Spacer(1, 2 * mm))

    # Metadata table
    ev_meta = [
        [_l("URL", "URL", is_de), ev.url],
        [_l("Erfasst", "Captured", is_de), _fmt_dt(ev.captured_at, is_de)],
        [_l("Prüfsumme", "Hash", is_de), ev.content_hash],
    ]
    if ev.archived_url:
        ev_meta.append([_l("Archiv", "Archive", is_de), ev.archived_url])

    meta_table = Table(ev_meta, colWidths=[35 * mm, 125 * mm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#475569")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 3 * mm))

    # Content (in a visually distinct block)
    elements.append(Paragraph(
        _l("Inhalt:", "Content:", is_de),
        styles["FieldLabel"]
    ))
    elements.append(Paragraph(
        f'<i>\u201e{_escape(ev.content_text)}\u201c</i>',
        styles["ContentQuote"]
    ))
    elements.append(Spacer(1, 3 * mm))

    # Classification
    if c:
        sev_label = _severity_label(c.severity, is_de)
        cats = ", ".join(cat.value for cat in c.categories)
        elements.append(Paragraph(
            f"<b>{_l('Schweregrad', 'Severity', is_de)}:</b> {sev_label} | "
            f"<b>{_l('Kategorien', 'Categories', is_de)}:</b> {cats} | "
            f"<b>{_l('Konfidenz', 'Confidence', is_de)}:</b> {c.confidence:.0%}",
            styles["Classification"]
        ))

        summary = c.summary_de if is_de else c.summary
        elements.append(Paragraph(summary, styles["Body"]))
        elements.append(Spacer(1, 2 * mm))

        # Applicable laws
        if c.applicable_laws:
            elements.append(Paragraph(
                _l("Anwendbare Gesetze:", "Applicable laws:", is_de),
                styles["FieldLabel"]
            ))
            for law in c.applicable_laws:
                title = law.title_de if is_de else law.title
                reason = law.applies_because_de if is_de else law.applies_because
                elements.append(Paragraph(
                    f"<b>{law.paragraph}</b> – {title}: {reason} "
                    f"({_l('Höchststrafe', 'Max penalty', is_de)}: {law.max_penalty})",
                    styles["LawItem"]
                ))

    elements.append(Spacer(1, 4 * mm))
    return elements


def _get_styles() -> dict:
    base = getSampleStyleSheet()
    styles = {}

    styles["Title"] = ParagraphStyle(
        "SVTitle", parent=base["Title"],
        fontSize=22, textColor=colors.HexColor("#4338ca"),
        spaceAfter=2 * mm,
    )
    styles["Subtitle"] = ParagraphStyle(
        "SVSubtitle", parent=base["Normal"],
        fontSize=10, textColor=colors.HexColor("#64748b"),
    )
    styles["ReportType"] = ParagraphStyle(
        "SVReportType", parent=base["Heading1"],
        fontSize=14, textColor=colors.HexColor("#1e293b"),
        spaceBefore=4 * mm, spaceAfter=2 * mm,
    )
    styles["SectionHead"] = ParagraphStyle(
        "SVSection", parent=base["Heading2"],
        fontSize=12, textColor=colors.HexColor("#1e293b"),
        spaceBefore=4 * mm, spaceAfter=2 * mm,
    )
    styles["EvidenceHead"] = ParagraphStyle(
        "SVEvHead", parent=base["Heading3"],
        fontSize=11, textColor=colors.HexColor("#4338ca"),
        spaceBefore=3 * mm, spaceAfter=1 * mm,
    )
    styles["Body"] = ParagraphStyle(
        "SVBody", parent=base["Normal"],
        fontSize=9, leading=13, textColor=colors.HexColor("#334155"),
    )
    styles["FieldLabel"] = ParagraphStyle(
        "SVFieldLabel", parent=base["Normal"],
        fontSize=8, textColor=colors.HexColor("#64748b"),
        spaceBefore=1 * mm,
    )
    styles["ContentQuote"] = ParagraphStyle(
        "SVQuote", parent=base["Normal"],
        fontSize=9, leading=13, textColor=colors.HexColor("#1e293b"),
        leftIndent=10 * mm, borderColor=colors.HexColor("#e2e8f0"),
        borderWidth=0, borderPadding=4,
        backColor=colors.HexColor("#f8fafc"),
    )
    styles["Classification"] = ParagraphStyle(
        "SVClass", parent=base["Normal"],
        fontSize=8, leading=12, textColor=colors.HexColor("#475569"),
        spaceBefore=2 * mm, spaceAfter=2 * mm,
    )
    styles["LawItem"] = ParagraphStyle(
        "SVLaw", parent=base["Normal"],
        fontSize=8, leading=11, textColor=colors.HexColor("#475569"),
        leftIndent=5 * mm, spaceBefore=1 * mm,
    )
    styles["Footer"] = ParagraphStyle(
        "SVFooter", parent=base["Normal"],
        fontSize=7, textColor=colors.HexColor("#94a3b8"),
        alignment=1,  # center
    )

    return styles


def _l(de: str, en: str, is_de: bool) -> str:
    return de if is_de else en


def _severity_label(severity, is_de: bool) -> str:
    if isinstance(severity, str):
        s = severity
    else:
        s = severity.value
    labels_de = {"low": "Niedrig", "medium": "Mittel", "high": "Hoch", "critical": "KRITISCH"}
    labels_en = {"low": "Low", "medium": "Medium", "high": "High", "critical": "CRITICAL"}
    return (labels_de if is_de else labels_en).get(s, s)


def _fmt_dt(dt, is_de: bool) -> str:
    if isinstance(dt, str):
        dt = datetime.fromisoformat(dt)
    if is_de:
        return dt.strftime("%d.%m.%Y %H:%M Uhr")
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def _escape(text: str) -> str:
    """Escape XML special chars for ReportLab Paragraph."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
